### ISSUE TITLE
Verify model performance based on benchmark data

### ISSUE THREAD

**Issue by t-tte** [uber/causalml#109]
As discussed on issue #70, it would be valuable to replicate the benchmark tests from the foundational research papers. For the meta-learners, we have the papers by [Nie and Wager (2019)]((https://arxiv.org/abs/1712.04912)) and [Kunzel et al (2019)]() that contain such benchmark studies.

The simulation studies are:

	•	Simulation setups A, B, C and D (Nie and Wager, p. 16)
	•	Simulations 1—6 (Kunzel et al, p. 15–19)

Additionally, both of the papers have experiments with real data:

	•	Voting study 1 (Nie and Wager, p. 7)
	•	Voting study 2 (Kunzel et al, p. 9)
	•	Canvassing study (Kunzel et al, p. 10)

It seems to me like a good starting point would be to conduct the experiments with synthetic data, but I’m also interested in hearing what others think.

As @swager mentioned, the replication data for Nie and Wager (2019) are available [here](https://github.com/xnie/rlearner/tree/master/experiments_for_paper).

**Comment by MaximilianFranz** [comment]
Hey @t-tte, I've started working on the mentioned comparison using our [JustCause framework](https://github.com/inovex/justcause) and wanted to highlight a few ideas/notes/problems. 

1. I've started using `rpy2` in order to use the original rlearner implementation directly from Python.  However, as I am not familiar with the method in detail, it is hard to know, how to use the RLearner from causalml in order to get the closest possible imitation. (As the goal for me would be to show how the R implementation fares against the Python implementation) 

2. I've reimplemented the benchmarking data (A to D) from Nie and Wager inside the JustCause framework to allow easy usage. 

First results are a little confusing as in one case (boost) the R implementation is significantly better while in the other (lasso) the Python Version is much better. So much even, that there seems to be some mistake..  (using only 100 replications of the IHDP dataset, the simulation data from Nie and Wager will follow): 

<img width="719" alt="Rlearner with XGBoost" src="https://user-images.githubusercontent.com/23345908/71764079-70043800-2ee3-11ea-96c0-570005b5ec12.png">
<img width="748" alt="Rlearner with GLMNET" src="https://user-images.githubusercontent.com/23345908/71764080-70043800-2ee3-11ea-8d4c-56f470b72b8b.png">

I'll publish the notebook soon and let you know about the progress I'll make on this. However, I'll limit myself to 1 or 2 benchmark datasets.

**Comment by t-tte** [comment]
Hi @MaximilianFranz 

Thanks for the note! Great to hear you've started working on this, and that you've implemented some of the simulations in [JustCause](https://github.com/inovex/justcause). I'll have a closer look and will keep you updated.

As to the differences between the methods, that's indeed a tricky one. My first two hypotheses would be:

- The base-learners or some of their parameters are set differently
- The propensity score is calculated differently

If you share your notebook, I'll be very happy to dig deeper to see where the root cause of the differences might be.

**Comment by MaximilianFranz** [comment]
Hey again, 

The notebook is on a separate branch [here](https://github.com/inovex/justcause/blob/rlearner-comparison/notebooks/rlearner-comparison.ipynb), since we're still changing stuff within the JustCause API. I haven't looked at it in detail yet, but will return to it once we've finished our fully documented version.

**Comment by t-tte** [comment]
This issue was partly addressed in PR #443. As I have no immediate plans to work on the remaining simulations, I'm closing the issue.
