### ISSUE TITLE
Example in Synthetic Data Generation Process

### ISSUE THREAD

**Issue by clfeutry** [uber/causalml#149]
When I try to execute the code given in the examples section for the synthetic data generation process. The importation of `causalml.metrics.synthetic` failed : `ModuleNotFoundError: No module named 'causalml.metrics.synthetic'`
After some research the function synthetic_data that I wished to use was in causalml.dataset

**Comment by ppstacy** [comment]
Hi @clfeutry, thanks for finding this! Could you please point us which example notebooks you were looking at? Because I checked the [meta_learners_with_synthetic_data.ipynb](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data.ipynb) and [meta_learners_with_synthetic_data_multiple_treatment.ipynb](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb) both look right for me. Thanks!

**Comment by paullo0106** [comment]
clfeutry was probably referring to [example.rst](https://github.com/uber/causalml/blob/master/docs/examples.rst#single-simulation). In `Single Simulation` and `Multiple Simulations` sections, looks like there is no `synthetic.py` in `causalml.metrics` anymore, I'll submit a PR to update the docs : )

```
from causalml.dataset.synthetic import *
from causalml.metrics.synthetic import *

# Generate synthetic data for single simulation
y, X, treatment, tau, b, e = synthetic_data(mode=1)
y, X, treatment, tau, b, e = simulate_nuisance_and_easy_treatment()
```

**Comment by clfeutry** [comment]
Yes I was exactly referring to example.rst, Thank you @paullo0106. Sorry for the delay in my response and the lack of precision in my first message @ppstacy
