### ISSUE TITLE
Wrong requirements when installing causalml via pip

### ISSUE THREAD

**Issue by MaximilianFranz** [uber/causalml#154]
**Describe the bug**
When installing via pip this error occurs 

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from causalml) (from versions: none)
ERROR: No matching distribution found for tensorflow (from causalml)
``` 

**To Reproduce**

 - Setup new conda environment with python (Python 3.8.1) and pip (pip 20.0.2)
 - `pip install causalml` 

**Expected behavior**
Working installation via pip

**Environment (please complete the following information):**
 - OS: Ubuntu

**Comment by jeongyoonlee** [comment]
Thanks for the report, @MaximilianFranz.

This is because `tensorflow`, which is required for `inference.nn.DragonNet`, does not support Python 3.8 yet (ref: [Tensorflow website](https://www.tensorflow.org/install)).

For now, I think that we just need to wait until `tensorflow` add Python 3.8 support.

**Comment by jeongyoonlee** [comment]
`tensorflow` now supports Python 3.8, and `causalml` installation in Python 3.8 works without an error.
