### ISSUE TITLE
How to get booster for XGBoost learner

### ISSUE THREAD

**Issue by yogi22** [uber/causalml#210]
Hi,
   I was trying to extract from an XGBoost learner, similar to how it is done in XGBoost but I get the following message
"XGBoostError: need to call fit or load_model beforehand."
I am fitting the model before trying to extract the model. The screenshot has the commands and error message.

![causalml_error](https://user-images.githubusercontent.com/7282681/87445378-d82b8900-c5ac-11ea-914f-bf6ab531ba63.png)

Thanks

**Comment by jeongyoonlee** [comment]
Thanks for trying causalml, @yogi22. To access the base learner within the meta-learner (in this case, `BaseSRegressor`), you need to access `learner_t.models[t_index]` where `t_index` is the index of the treatment group you're interested. If you have only one treatment group instead of multiple treatment groups, `t_index` will be `0`.

This is to support multiple treatment groups in meta-learners. 

Please let me know if it resolves the issue.

Thanks,

**Comment by yogi22** [comment]
Thanks for the quick response. Just as an FYI, I was just trying the example in "meta_learners_with_synthetic_data.ipynb". 

I was able to extract the booster using t_index as 1. learner.models dict had just one model with index 1. I have a followup question. I was trying to predict the CATE for test data using only the X matrix, (without treatment and outcome as they are not available for test data). I am able to do it using the XGBRegressor object but if I extract the booster from the XGBRegressor then the booster  is expecting one more column (for the predict function) than what is available in the X matrix. I am not sure what the extra column is. I am thinking it's probably the treatment column but was not sure.

**Comment by jeongyoonlee** [comment]
The extra column in `BaseSRegressor` is for the treatment because S-learner adds a variable for the treatment to the input feature matrix of the base model,  and calculate the difference between `E[Y | X, A=1] - E[Y | X, A=0]` where `Y` is the outcome, `X` is the covariate/feature matrix, and `A` is the treatment.

If you want to generate predictions regardless the treatment, you can either take the average of predictions with `A==0` and `A==1`.

**Comment by yogi22** [comment]
thanks this answers my question
