### ISSUE TITLE
Question on uplift curve with multiple treatments

### ISSUE THREAD

**Issue by deeplaunch** [uber/causalml#234]
In the tutorial **[uplift_trees_with_synthetic_data](https://github.com/uber/causalml/blob/master/examples/uplift_trees_with_synthetic_data.ipynb)**, the author compares the treatments which happen to have the highest predicted CATE (let's call it "synthetic treatment") with the control group. 

Is there some selection problem here? Specifically, by definition this will skip the subset for which none of the treatment is better than control (this group is not in "synthetic treatment", but in "control").

If this is the case, should it be added to the "synthetic treatment" group?

On a related note, what the uplift curve doesn't seem to tell us is how much gain we can have by having the option to assign different treatment to our population (vs. the single treatment with the largest ATE). Sometimes even if our AUUC does not look good, such differentiated treatment can still be helpful particularly when we don't have a budget constraint. Is this understanding correct?

Sorry if my wording is too ambiguous. Do let me know if more clarification is needed. 

Thanks!

**Comment by jeongyoonlee** [comment]
Thanks for the question, @deeplaunch. I added the author of the notebook, @t-tte so that he can answer to your question when he's available, but, meanwhile, let me try to provide my answers.
> Is there some selection problem here? Specifically, by definition this will skip the subset for which none of the treatment is better than control (this group is not in "synthetic treatment", but in "control").
> 
> If this is the case, should it be added to the "synthetic treatment" group?

For those whom no treatment is better than control for, the recommended `treatment` by the uplift model is indeed `control`. Therefore, it's correct to assign them to `control` instead of `synthetic treatment`.

> On a related note, what the uplift curve doesn't seem to tell us is how much gain we can have by having the option to assign different treatment to our population (vs. the single treatment with the largest ATE). Sometimes even if our AUUC does not look good, such differentiated treatment can still be helpful particularly when we don't have a budget constraint. Is this understanding correct?

Actually, that's exactly what "synthetic treatment" is doing. With the synthetic treatment, we selected the treatment with the highest CATE estimate for each individual. Therefore, the uplift curve in the notebook shows the gain we'd get by selecting the best treatment for each individual.

> Sorry if my wording is too ambiguous. Do let me know if more clarification is needed.
> 
> Thanks!

No worries. Please let me know if you have any more questions. Thanks for your question.

**Comment by t-tte** [comment]
Thanks for the very good question @deeplaunch! @jeongyoonlee already provided some great clarifications above. The only thing I'd like to add is that there are multiple ways in which you could construct the contrast against which you evaluate the performance of an uplift model. In more recent work, I've preferred the approach set out in [Kapelner et al 2014](https://arxiv.org/abs/1404.7844) in which the treatment recommended by the uplift model is compared against alternative allocation strategies in an unseen sample. An example of this approach can be found in the [unit selection notebook](https://github.com/uber/causalml/blob/master/examples/counterfactual_value_optimization.ipynb). There is also a [recent paper](https://link.springer.com/article/10.1007/s10618-019-00670-y) that has an overview of the various model comparison approaches that have been proposed.

**Comment by deeplaunch** [comment]
Thank you both for such detailed answers @jeongyoonlee and @t-tte -they're very helpful.  

Will check out the papers too! cc'ed @mavpanos
