### ISSUE TITLE
Make meta-learners compatible with pandas.DataFrame inputs

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#29]
Currently meta-learners functions expect `numpy.matrix` as an input. e.g.  `inference.meta.LRSLearner.estimate_ate()` fails when the input is `pandas.DataFrame` instead of `numpy.matrix`.

It'd be better to make these compatible with `pandas.DataFrame` inputs.

**Comment by peterfoley** [comment]
I'm happy to take a stab at this one. Are there strong feelings on how to handle inputs that aren't purely numeric?
My default design would be to have it throw an exception if non-numeric columns exist, basically [the same setup as xgboost uses](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L291).

**Comment by yungmsh** [comment]
Hey @peterfoley thanks for the comment. I'm implementing a simpler helper method that converts anything that's a pd.DataFrame or pd.Series into an np.ndarray. Preserving column names shouldn't be an issue at the scope we're concerned with since we're directly passing these arrays into the base learner under the hood anyway. cc @jeongyoonlee: But in future iterations we might want to store the column names and X as well (right now we don't store X), so that feature importances can be calculated without feeding in a new X (akin to how most `.feature_importances_` are called). I guess in that case we would make X optional in .get_importances(...). Anyway that's all to say, I'll push a simple update soon and feel free to improve upon it in a way that's similar to xgboost afterwards!

**Comment by yungmsh** [comment]
Re: raising exceptions for non-numeric types, I don't think we need to at this point, since the estimators themselves (provided by user) should already be catching that

**Comment by yungmsh** [comment]
PR here: https://github.com/uber/causalml/pull/97

**Comment by peterfoley** [comment]
Thanks @yungmsh ! I'd already started on some work too, so I added some thoughts in [a PR comment](https://github.com/uber/causalml/pull/97#issuecomment-562353070)

**Comment by jeongyoonlee** [comment]
Merged into master with #97
