### ISSUE TITLE
Same results for T-Learner (LR) and X-Learner (LR)

### ISSUE THREAD

**Issue by baendigreydo** [uber/causalml#302]
I reproduced your [notebook](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data.ipynb) here, esp. part B for validation. My results as well as your result is that the T-Learner (LR) and X-Learner (LR) have the same results and I highly doubt this to be correct. From the methodological standpoint, they are not the same (obviously).

When looking at the train_summary and valid_summary you give, the results are the same. Plotting the distributions leads to the same conclusion (T-learner is hidden behind X-learner curve.), as well as the calculation of the AUUC. When checking for similarity of the CATE predictions, they seem not to be equal even though results are the same up to the 8th decimale.

In case I am just completely wrong, a clarification about why both models should  deliver the same results would be great. Thank you.

**Comment by paullo0106** [comment]
@huigangchen might be able to provide some intuition why this might happen

**Comment by huigangchen** [comment]
Yes, if LR is used for T-Learner and X-Learner, the results should be the same, since the linear function is additive. For example, during tau estimation in X-learner, the estimated models for both treated population and the control population should just be the difference between the treatment model and the control model, which is the same as the final outcome of T-Learner.
