### ISSUE TITLE
Problem about Learner

### ISSUE THREAD

**Issue by CaptainFan** [uber/causalml#310]
Hi,

I am new to the causal machine learning area and it is exciting to see excellent work you have done. I try to learn the use of causalml package and I have a problem related to meta-learner part.

Does the implementation of X-learner automatically adjust for confounders? It seems that it does but I have not found details.

As I understand it, for example, the Athey's causalTree package requires either RCT data or observational data that is pre-adjusted for confounding before estimating the heterogeneous effects.  So, the variables that are passed to causalTree may be different from the ones that may be required for adjusting for confounding (in case of observational data). That is why I am not sure for causalml package, meta-learenr part, whether obsersetional data should be adjusted manually. 

Looking forward to hearing from you soon. Thank you so much!

Best

**Comment by t-tte** [comment]
Hello

Thanks for the question. The answer depends on what you mean by "automatic adjustment". On the one hand, if you have already selected the [right controls](https://ftp.cs.ucla.edu/pub/stat_ser/r493.pdf), then in principle you could use those features directly in the relevant learner. In practice, many people do matching first and try to learn treatment effect heterogeneity in the matched sample. I imagine this is what you're referring to when you talk about the causalTree package. Matching is also fine, although it changes the population in which you are estimating the treatment effects (because you are throwing non-matched samples away).

If, on the other hand, you haven't yet selected the right controls, the meta-learners (or any other method out there) cannot do this for you. In particular, if you're dealing with observational data, you should avoid "throwing everything in" and assuming this helps with confounding.

**Comment by CaptainFan** [comment]
Thank you so much for you reply! Really appreciate that you were willing to take out time to answer my question.  

To avoid throwing non-matched samples away, I pre-process the data by weighting the sample using propensity score calculated on X(all the covariants) to create a pseudo population and pass that to the meta-Learner. Is this a better choice to use meta-learener for ATE or CATE estimation when the orgianl datasets are observational data?

Thanks again!

**Comment by t-tte** [comment]
It's my pleasure! First, if you have correctly weighted the population, then it's not clear to me why you would want to use a meta-learner to estimate the ATE. You can estimate it using a standard method such as [weighted regression](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4626409/).

Second, I can't see why it would be helpful to create a synthetic population and estimate CATEs in that population rather than just use the features in the relevant meta-learner directly. Admittedly, I haven't seen any research on the topic either. Let me know if you can find any references related to this: I'd be curious to have a look.

**Comment by CaptainFan** [comment]
Thank you for your reply! 
Here is the reason why I pre-process the data by weighting the sample using propensity score calculated on X(all the covariants) to create a pseudo population. 
According to (Künzel, S. R., Sekhon, J. S., Bickel, P. J., & Yu, B. (2019). Metalearners for estimating heterogeneous treatment effects using machine learning. Proceedings of the national academy of sciences, 116(10), 4156-4165.)
they mentioned that "When used with trees, this has been called the “two-tree” estimator, and we will therefore refer to the general mechanism of estimating the response functions separately as the “T-learner,” with “T” being short for “two.”". 
in paper (Athey, S., & Imbens, G. (2016). Recursive partitioning for heterogeneous causal effects. Proceedings of the National Academy of Sciences, 113(27), 7353-7360.)
They discused that "The discussion so far has focused on the setting where the assignment to treatment is randomized. The proposed methods can be adapted to observational studies under the assumption of unconfoundedness. In that case we need to modify the estimates within leaves to remove the bias from simple comparisons of treated and control units. There is a large literature on methods for doing so (e.g., ref. 3). For example, as in ref. 21 we can do so by propensity score weighting. Efficiency will improve if we renormalize the weights within each leaf and within the treatment and control group when estimating treatment effects." 

From this angle, I think leaner with tree-based method is close to causalTree, so I follow the method in causalTree literature to modify the dataset.

Look forward to hearing you again! Thank you so much!

**Comment by t-tte** [comment]
Thank you, those are useful references.

Coincidentally, there is a [brand new paper](https://www.aaai.org/AAAI21Papers/AAAI-8987.JungY.pdf) that tackles the problem head on. I haven't had time to review it yet but suspect it'll be worth implementing in Causal ML.

**Comment by CaptainFan** [comment]
Thank you so much for your help!
