### ISSUE TITLE
How Counterfactuals are estimated

### ISSUE THREAD

**Issue by BrianMiner** [uber/causalml#340]
I was hoping to get a better idea of how to construct the counterfactuals E[Y | X,T] where Y is the outcome, X are features and T is the treatment, from the CATE estimates. I wasn't sure I followed the example code description.

If there are 5 treatments A,B,C,D,E and a model, say uplift RF, is built and for any X generates the CATE estimates for B-A, C-A, D-A, E-A (i.e. A is the control treatment), how would the counterfactual estimates be constructed?

Is it the case that a regular supervised learning model is built to predict E[ Y | X, T] and for each observation (e.g. customer) the prediction is made setting T == A (the control). And then the CATE estimates are added to it?

So to get:

E[Y | X,T = A] = the supervised model estimate above
E[Y | X,T = B] = E[Y | X,T = A]  + CATE_{B-A}
...
E[Y | X,T = E] = E[Y | X,T = A]  + CATE_{E-A}

Is this what is happening or something else? Thanks!

**Comment by t-tte** [comment]
Hi @BrianMiner - thanks for the question! In fact, the way in which the control outcome is estimated is by calculating E[Y | X] and then subtracting the predicted CATE from a given learner from it. This is done because it makes it easy to plug the output from our CATE learners in the model. The step is actually redundant for some models (such as the R-Learner) which calculate E[Y | X] as an intermediate step.

**Comment by BrianMiner** [comment]
Hi @t-tte 

Sorry not sure I followed. 

If we have say an uplift random forest and three treatments (0,1,2) with control =0, we would have the CATE estimates for {0->1} and {0-2} which are the CATE for each treatment relative to the control. I think this is what is estimated by the model correct? 

Then how would the estimates for E[X, T=0] and E[X, T=1] and E[X, T=2]?

**Comment by t-tte** [comment]
Hi @BrianMiner 

That's right, the CATE learning methods return the uplifts from different treatments relative to control. If a unit is actually in Treatment 2, we estimate the outcome under control for that unit as YHAT0 = E[Y | X] - YHAT2, where YHAT2 is the predicted uplift for the unit under Treatment 2, according to our model. The outcome under Treatment 1 is again calculated as YHAT0 + YHAT1. And so on.

N.B. The purpose of all of the above is simply to work around the limitations of Causal ML API (the fact that we return only uplift predictions and for the treatment groups only, rather than the expected outcomes under each treatment condition including the control). It doesn't have any theoretical significance.
