### ISSUE TITLE
Anaconda Install "environment-py38.yml" Conflict

### ISSUE THREAD

**Issue by wsdqy1234** [uber/causalml#355]
I am using anaconda install. However, when I use
`conda env create -f environment-tf-py38.yml`,
the conflict appears as
![image](https://user-images.githubusercontent.com/53553706/124228702-24196a00-db3f-11eb-80ad-a141f1d409d7.png)

I'm very disappointed and wanna help. Please help me and I will be really appreciated.

**Comment by DanielDaCosta** [comment]
Having the same issue here

**Comment by DanielDaCosta** [comment]
Having the same problem here

**Comment by chazarnik** [comment]
Hi, I tried @DanielDaCosta 's solution and it does not work for me on Windows. In general building numpy from scratch does not play well in Windows-maybe it has something to do with that. 
Additionally, patsy 0.5.1 requires scipy 1.6.2 while 1.4.1 is listed on the yml file. 

I also tried to install everything except for the packages that @wsdqy1234 posted. Then I installed the ones left manually. Still no luck. Building stops with error code 1 Microsoft C++ 14 is required. Same for py-37. 
Any suggestions?

**Comment by wsdqy1234** [comment]
Finally, I have successfully installed `causalml-py36`, and I don't know why I cannot install other virtual environments. I think this may be helpful for someone who has the same problem.

**Comment by PetrarcaBruto** [comment]
Thank you @wsdqy1234 for pointing that causalml-py36 installs. I need to test it now.
BUT causal-tf-py36 doesn't install, it fails with the following errors.
  
          The conflict is caused by:
                The user requested grpcio==1.37.0
                tensorboard 2.5.0 depends on grpcio>=1.24.3
                tensorflow 2.5.0 depends on grpcio~=1.34.0
            
            To fix this you could try to:
            1. loosen the range of package versions you've specified
            2. remove package versions to allow pip attempt to solve the dependency conflict
            
            
            Pip subprocess error:
            ERROR: Cannot install -r c:\Users\petrarca\causalml\envs\condaenv.c9mk9rzi.requirements.txt (line 112), -r c:\Users\petrarca\causalml\envs\condaenv.c9mk9rzi.requirements.txt (line 115) and grpcio==1.37.0 because these package versions have conflicting dependencies.
            ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
            
            failed
            
            CondaEnvException: Pip failed

It is shame that we cannot use the new functionality due to an installation error. Please Uber people make a fix available to continue your good work.
Thanks

**Comment by paullo0106** [comment]
Hello folks, thanks for raising this issue. Similar to issue #350, we think it's because the PR #343 hasn't been published to PyPI yet. To use latest master, you can install CausalML from the GitHub repo directly.

We are publishing CausalML v0.11 in the next few days and hope the installation will be more straightforward for everyone.

cc: @jeongyoonlee
