### ISSUE TITLE
CounterfactualValueEstimator only supports discrete outcome?

### ISSUE THREAD

**Issue by DonCorle0ne** [uber/causalml#390]
Hi guys, thanks a lot for this amazing package. I'm trying to use this package to deal with problems with continuous outcome. I see CounterfactualValueEstimator has the capability to calculate counterfactuals, but seems like only for discrete outcome, say binary ones. Am I misunderstanding anything here? Does this package support calculating counterfactuals of continuous outcome?

**Comment by ZSCDumin** [comment]
It&nbsp; doesn't support calculating counterfactuals of continuous outcome.



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 1, 2021 07:12 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [uber/causalml] CounterfactualValueEstimator only supports discrete outcome? (#390)




 
Hi guys, thanks a lot for this amazing package. I'm trying to use this package to deal with problems with continuous outcome. I see CounterfactualValueEstimator has the capability to calculate counterfactuals, but seems like only for discrete outcome, say binary ones. Am I misunderstanding anything here? Does this package support calculating counterfactuals of continuous outcome?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
