### ISSUE TITLE
Add random_state to upliftTreeClassifier and upliftRandomForestClassifier

### ISSUE THREAD

**Issue by flippercy** [uber/causalml#401]
So far the prediction of upliftTreeClassifier and upliftRandomForestClassifier is not repeatable, which is probably due to the missing of random_state. Could someone add this as a parameter, please?

Thank you.

**Comment by manojbalaji1** [comment]
@paullo0106 I think we need to use randomstate rather than np.random.seed(42). I think there's this issue raised that  np.random,seed is not thread-safe. I think that should be the issue. Let me investigate this problem and try to fix it

Reference: https://stackoverflow.com/questions/7029993/differences-between-numpy-random-and-random-random-in-python

**Comment by jeongyoonlee** [comment]
Added in #422.
