### ISSUE TITLE
Speed up UpliftRandomForestClassifier?

### ISSUE THREAD

**Issue by BrianMiner** [uber/causalml#54]
I am trying to fit this with only 100 trees on a dataset of roughly 200,000 records and 80 features. It takes hours to fit (and the results so far has been poor - overfit it appears, I am tuning some regularization as we speak). I am wondering if there this speed is normal and if there are any plans to improve (I did not see any option to grow the trees in parallel)? Also - on a real world data set (say from a marketing response problem) has this implementation proved to predict well?

**Comment by zhenyuz0500** [comment]
Hi BrianMiner,

Thanks for the feedback!

Here are some comments and thoughts:
(1) Yes, uplift trees (KL, ED, CHI, CTS) are slow for handling large dataset for now 
(2) There is a plan to accelerate these algorithms, but it will not be implemented in the next couple months
(3) You can focus on meta learners, such as two models, x-learner, and r-learner for now, since they are relatively fast
(4) based on my experience, KL, CHI, ED are performing similarly, to save time, you can choose one of these three for training instead of all. We haven't found CTS outperforming other methods in our studies.
(5) If the features are good enough, the treatment effect is significant in ATE for the original experiment, then the uplift models would predict well - we have use cases launched in experiments that proved the models were able to provide significant results.

Hope it helps!

**Comment by paullo0106** [comment]
Just some ideas on the UpliftTree optimization, we can probably start from [growDecisionTreeFrom()](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L850) in the _UpliftTreeClassifier_ class:

- **Pre-sort**: sort the dataset in the beginning, and use the sorted vectors at each node evaluation (reference - _presort_ in [sklearn's BaseDecisionTree](https://github.com/scikit-learn/scikit-learn/blob/1495f6924/sklearn/tree/tree.py#L330))
- **Split**:   ([sklearn's tree splitter](https://github.com/scikit-learn/scikit-learn/blob/1495f69242646d239d89a5713982946b8ffcf9d9/sklearn/tree/_splitter.pyx#L300))
  - Do the actual data set split after finding the best candidate 
  - When the variable is numerical, instead of re-creating datasets repeatedly, use a linear algorithm that incrementally subtracts from the left and adds to the right bins to compute the new values for two bins per the splitting value.
  - Avoid evaluating again on the binary variables which were used along the route
 
These are very high-level thoughts, look forward to learning the ideas from others :)

**Comment by jeongyoonlee** [comment]
I started to work on it and made some improvement with #108. Will look into what @paullo0106 suggested. Thanks!

**Comment by Dvirbeno** [comment]
> I am trying to fit this with only 100 trees on a dataset of roughly 200,000 records and 80 features. It takes hours to fit 

Note that that part on the current release implementation:
(Under UpliftTreeClassifier.growDecisionTreeFrom())


`


            # unique values
            lsUnique = np.unique(columnValues)

            if (isinstance(lsUnique[0], int) or
                    isinstance(lsUnique[0], float))
            ):
                if len(lsUnique) > 10:
                    lspercentile = np.percentile(columnValues, [3, 5, 10, 20, 30, 50, 70, 80, 90, 95, 97])
                else:
                    lspercentile = np.percentile(lsUnique, [10, 50, 90])
                lsUnique = np.unique(lspercentile)`

Practically, it means that if your input features do not comply with the IF condition above, every single unique value of the examined feature will be considered as a candidate split (a great amount of values for 'continuous' features). 
It seems that if your input data is of dtype np.float16, for example, the condition expression is evaluated as False, and all the unique values of the feature are tested.
I guess that might be a problem here, so maybe try to cast your input data and verify only the specified percentiles are evaluated as candidate splits.

**Comment by jeongyoonlee** [comment]
Thanks @Dvirbeno for pointing this out. I fixed it in #420.
