### ISSUE TITLE
CausalTreeRegressor with the paramters 'criterion :got an unexpected keyword argument 'criterion',and min_impurity_split not in params but got an unexpected keyword argument 'min_impurity_split' 

### ISSUE THREAD

**Issue by exuding** [uber/causalml#542]
**Describe the bug**
CausalTreeRegressor with the paramters 'criterion :got an unexpected keyword argument 'criterion',and min_impurity_split not in params but got an unexpected keyword argument 'min_impurity_split' 。

**To Reproduce**
  when run:
  tree1 = CausalTreeRegressor(control_name=0,
                              max_depth=7, 
                              min_samples_leaf=100, 
                              random_state=122)
  tree1.fit(X=X_train.values,
            treatment=treatment_train,
            y=y_train)
  get:
  TypeError: __cinit__() got an unexpected keyword argument 'min_impurity_split'

**Environment (please complete the following information):**
 - OS: [CentOS]
 - Python Version: [3.7.13]
 - Versions of Major Dependencies : causalml=0.12.3]

**Comment by jeongyoonlee** [comment]
Thanks for reporting this issue, @exuding. This is due to latest `scikit-learn` removed `min_impurity_split` from their tree implementations, which `CausalTreeRegressor` depends on.

This issue got fixed in #522 by @alexander-pv with many more improvements. We will release a new version of `causalml` soon, but meanwhile, you can install the latest `causalml` from the repo directly.

**Comment by jeongyoonlee** [comment]
Hi @exuding, could you try v0.13.0, which was released last week with the fix?
