### ISSUE TITLE
build fails in test_causal_trees.py, no attribute _support_missing_values

### ISSUE THREAD

**Issue by ras44** [uber/causalml#733]
**Describe the bug**
Builds are failing with a new error:

```
FAILED tests/test_causal_trees.py::TestCausalRandomForestRegressor::test_fit[5] - AttributeError: 'CausalTreeRegressor' object has no attribute '_support_missing_values'
```

See build at: https://github.com/uber/causalml/actions/runs/7626474561/job/20772942656?pr=722

**To Reproduce**

Follow build at: https://github.com/uber/causalml/actions/runs/7626474561/job/20772942656?pr=722

**Expected behavior**
No failure during build

**Screenshots**
![image](https://github.com/uber/causalml/assets/9282281/bf659421-4300-45da-9be0-2553107818e0)

**Environment (please complete the following information):**
See build at: https://github.com/uber/causalml/actions/runs/7626474561/job/20772942656?pr=722

**Additional context**
N/A

**Comment by jeongyoonlee** [comment]
This is due to the recent change in scikit-learn introduced by scikit-learn/scikit-learn#26391, which added `_support_missing_values()` to `_tree._classes.py` that is called by `ensemble._validate_X_predict()`.

We can either add `_support_missing_values()` to our `_tree._class.py` or add our own `_validate_X_predict()` for CausalTreeRegressor/CausalRandomForestRegressor.

@alexander-pv, what do you think? I will leave it to you.

**Comment by alexander-pv** [comment]
Hi, @ras44, @jeongyoonlee, thanks for asking!

I suggest adding `_support_missing_values()` `to _tree._class.py` with a temporary placeholder since the issue is directly related to https://github.com/scikit-learn/scikit-learn/pull/23595 where they updated cython backend for that.
I've opened PR https://github.com/uber/causalml/pull/734.

 Since I am working on a multiple treatment groups feature in causal trees which is also mainly related to cython, I think I will be able to add missing values support after finishing my WIP idea.
