### ISSUE TITLE
maq git repo dependency blocks pypi publish

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#738]
**Describe the bug**

We can't publish a new version to PyPI as it doesn't allow publishing a package with git repo dependencies (ref: pypi/warehouse#9404).

**To Reproduce**
```
python -m twine upload dist/*
```

**Expected behavior**
A new package is to be uploaded to PyPI without error.

**Screenshots**

```
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                                                                                                        
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                                                                                               
         Invalid value for requires_dist. Error: Can't have direct dependency: 'maq @ git+https://github.com/grf-labs/maq.git@py0.2.2#egg=maq&subdirectory=python-package'      
```

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by erikcs** [comment]
Hi @jeongyoonlee, sorry, I thought [we touched potential dep issues here](https://github.com/uber/causalml/pull/729#issuecomment-1884055255)

Unfortunately, I don't currently have the bandwidth to put together a pypi source release, as making a sdist with C++ that installs/compiles w/o issues on all the possible system configurations out there can be challenging. It could risk making further complications for a causalML install.

git + pip was nice since that takes care of everything. Since that turns out not be viable option, what about the following:

- Remove `maq` from  the pyproject.toml deps
- Remove maq from metrics/init and test_metrics

Then:
 - keep the maq example in the online /docs, but highlight that this example requires the optional package `maq` to be installed via ```pip install "git+https://github.com/grf-labs/maq.git#egg=maq&subdirectory=python-package"``` (+ make the appropriate edits to that notebook).
 - add a pip+git install of maq in the online docs builds https://github.com/uber/causalml/tree/master/.github/workflows in case your causalML doc system actually runs the code in the jupyter notebooks and not just renders them?

**Comment by ras44** [comment]
Just refreshed to see the updates from @erikcs addressing this issue 2 days ago.  Feel free to ignore my recent pushes doing the same!
